### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by kzpromo** [nil0x42/phpsploit#39]
Hello, how can i solve this problem?

Traceback (most recent call last):
  File "D:\phpsploit\phpsploit", line 22, in <module>
    import core
  File "D:\phpsploit\src\core__init__.py", line 16, in <module>
    from .config import userdir
  File "D:\phpsploit\src\core\config.py", line 13, in <module>
    from datatypes import Path
  File "D:\phpsploit\src\datatypes__init__.py", line 47, in <module>
    from .ByteSize import ByteSize
  File "D:\phpsploit\src\datatypes\ByteSize.py", line 1, in <module>
    from ui.color import colorize
  File "D:\phpsploit\src\ui__init__.py", line 68, in <module>
    from . import input
  File "D:\phpsploit\src\ui\input__init__.py", line 17, in <module>
    from .expect import Expect
  File "D:\phpsploit\src\ui\input\expect.py", line 6, in <module>
    from ..output import isatty
  File "D:\phpsploit\src\ui\output__init__.py", line 40, in <module>
    isatty = sys.**stdout**.isatty
AttributeError: 'NoneType' object has no attribute 'isatty'

**Comment by nil0x42** [comment]
it looks like you are using phpsploit on windows, and last time i tested the tool on windows was years ago.
in the week i ll try to run it in a virtual windows machine, in order to see how to fix this issue.

for the moment, consider using linux

**Comment by nil0x42** [comment]
on line 40 of the "src\ui\output__init__.py" file, the code line does not matches the log you provided, as this line contains `isatty = sys.__stdout__.isatty` instead of `isatty = sys.stdout.isatty`.

i tried on windows and couldn't reproduce the bug, please send more informations
